version: "3"

services:
    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        image: vulnex-frontend
        ports:
            - "3001:80"
        security_opt:
            - no-new-privileges
        restart: always

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        image: vulnex-backend
        env_file: .env
        ports:
            - "3000:3000"
        security_opt:
            - no-new-privileges
        restart: always
